Repository hashicorp/terraform-provider-consul, pull requests merged in 2019-03, with the labels that each got.

#78 Add import support to `consul_key_prefix`
  consul/resource_consul_key_prefix.go
  website/docs/r/key_prefix.html.markdown
Labels: documentation, size/XS

#93 Fix example in data.consul_service documentation
  website/docs/d/service.html.markdown
Labels: documentation, size/XS

#86 Add the consul_autopilot_config resource
  consul/resource_consul_autopilot_config.go
  consul/resource_consul_autopilot_config_test.go
  consul/resource_provider.go
  website/consul.erb
  website/docs/r/autopilot_config.html.markdown
Labels: documentation, size/XL

#94 Add import support to `consul_prepared_query`
  consul/resource_consul_prepared_query.go
  consul/resource_consul_prepared_query_test.go
  website/docs/r/prepared_query.markdown
Labels: documentation, size/S

#80 Add ca_path attribute to provider configuration
  consul/config.go
  consul/resource_provider.go
  consul/resource_provider_test.go
  consul/test-fixtures/capath/ca.pem
  website/docs/index.html.markdown
Labels: documentation, size/S

#64 Add support for health-checks to consul_service
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/consul/NOTICE.md
  vendor/github.com/hashicorp/consul/api/README.md
  vendor/github.com/hashicorp/consul/api/acl.go
  vendor/github.com/hashicorp/consul/api/agent.go
  vendor/github.com/hashicorp/consul/api/api.go
  vendor/github.com/hashicorp/consul/api/catalog.go
  vendor/github.com/hashicorp/consul/api/connect_ca.go
  vendor/github.com/hashicorp/consul/api/connect_intention.go
  vendor/github.com/hashicorp/consul/api/debug.go
  vendor/github.com/hashicorp/consul/api/health.go
  vendor/github.com/hashicorp/consul/api/kv.go
  vendor/github.com/hashicorp/consul/api/lock.go
  vendor/github.com/hashicorp/consul/api/operator_area.go
  vendor/github.com/hashicorp/consul/api/operator_keyring.go
  vendor/github.com/hashicorp/consul/api/semaphore.go
  vendor/github.com/hashicorp/consul/api/txn.go
  vendor/modules.txt
  website/docs/r/service.html.markdown
Labels: dependencies, documentation, size/XXL
