Repository hashicorp/terraform-provider-consul, pull requests merged in 2019-08, with the labels that each got.

#138 Use consul_keys data source in the index.html example
  website/docs/index.html.markdown
Labels: documentation, size/XS

#141 Use service_id instead of name when registering health-checks
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
  go.sum
Labels: size/S

#142 Check id computed
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
Labels: size/XS
