Repository hashicorp/terraform-provider-consul, pull requests merged in 2019-10, with the labels that each got.

#127 Add the config_entry resource
  consul/resource_consul_config_entry.go
  consul/resource_consul_config_entry_test.go
  consul/resource_provider.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/consul/api/agent.go
  vendor/github.com/hashicorp/consul/api/api.go
  vendor/github.com/hashicorp/consul/api/catalog.go
  vendor/github.com/hashicorp/consul/api/config_entry.go
  vendor/github.com/hashicorp/consul/api/config_entry_discoverychain.go
  vendor/github.com/hashicorp/consul/api/connect_intention.go
  vendor/github.com/hashicorp/consul/api/discovery_chain.go
  vendor/github.com/hashicorp/consul/api/go.mod
  vendor/github.com/hashicorp/consul/api/go.sum
  vendor/github.com/hashicorp/consul/api/operator_license.go
  vendor/modules.txt
  website/consul.erb
  website/docs/r/config_entry.markdown
Labels: dependencies, documentation, size/XXL

#143 Make consul_service health-checks unordered
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
Labels: size/M

#145 Mark consul_service.check.status as computed
  consul/resource_consul_service.go
  website/docs/r/service.html.markdown
Labels: documentation, size/XS

#154 Update CHANGELOG for 2.6.0
  CHANGELOG.md
Labels: size/XS

#155 config.go properly sets TLS configuration
  CHANGELOG.md
  consul/config.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#156 Remove useless depends_on from documentation and tests of config_entry
  consul/resource_consul_config_entry_test.go
  website/docs/r/config_entry.markdown
Labels: documentation, size/XS
