Repository hashicorp/terraform-provider-consul, pull requests merged in 2019-09, with the labels that each got.

#148 Add meta attribute in the consul_service datasource
  consul/data_source_consul_service.go
  consul/data_source_consul_service_test.go
  website/docs/d/service.html.markdown
Labels: documentation, size/XS

#147 Fix plan for consul_service when there is multiple service instances
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
Labels: size/M

#140 Update tests for Consul 1.5.2
  consul/data_source_consul_service_health_test.go
Labels: size/XS
