Repository hashicorp/terraform-provider-consul, pull requests merged in 2019-05, with the labels that each got.

#107 Add Consul Connect support to prepared queries.
  consul/resource_consul_prepared_query.go
  consul/resource_consul_prepared_query_test.go
  website/docs/r/prepared_query.markdown
Labels: documentation, size/XS

#103 Make consul acl {token,policy} importable
  consul/resource_consul_acl_policy.go
  consul/resource_consul_acl_policy_test.go
  consul/resource_consul_acl_token.go
  consul/resource_consul_acl_token_test.go
  website/docs/r/acl_policy.html.markdown
  website/docs/r/acl_token.html.markdown
Labels: documentation, size/M

#109 Correctly set failover, dns and template when reading consul_prepared_query
  consul/resource_consul_prepared_query.go
  consul/resource_consul_prepared_query_test.go
Labels: size/L

#105 Use provider datacenter as default when the agent cannot be reached
  consul/data_source_consul_agent_config.go
  consul/data_source_consul_agent_self.go
  consul/data_source_consul_autopilot_health.go
  consul/data_source_consul_key_prefix.go
  consul/data_source_consul_keys.go
  consul/data_source_consul_nodes.go
  consul/data_source_consul_service.go
  consul/data_source_consul_services.go
  consul/query_options.go
  consul/resource_consul_acl_policy.go
  consul/resource_consul_acl_policy_test.go
  consul/resource_consul_acl_token.go
  consul/resource_consul_acl_token_test.go
  consul/resource_consul_agent_service.go
  consul/resource_consul_agent_service_test.go
  consul/resource_consul_autopilot_config.go
  consul/resource_consul_autopilot_config_test.go
  consul/resource_consul_catalog_entry.go
  consul/resource_consul_catalog_entry_test.go
  consul/resource_consul_intention.go
  consul/resource_consul_intention_test.go
  consul/resource_consul_key_prefix.go
  consul/resource_consul_key_prefix_test.go
  consul/resource_consul_keys.go
  consul/resource_consul_keys_test.go
  consul/resource_consul_node.go
  consul/resource_consul_node_test.go
  consul/resource_consul_prepared_query.go
  consul/resource_consul_prepared_query_test.go
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
  consul/resource_provider.go
  website/docs/d/autopilot_health.html.markdown
  website/docs/d/key_prefix.html.markdown
  website/docs/d/keys.html.markdown
  website/docs/d/nodes.html.markdown
  website/docs/r/autopilot_config.html.markdown
  website/docs/r/catalog_entry.html.markdown
  website/docs/r/intention.html.markdown
  website/docs/r/key_prefix.html.markdown
  website/docs/r/keys.html.markdown
  website/docs/r/node.html.markdown
  website/docs/r/prepared_query.markdown
  website/docs/r/service.html.markdown
Labels: size/L

#104 Fix consul_node not detecting changes
  consul/resource_consul_node.go
  consul/resource_consul_node_test.go
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
  website/docs/r/service.html.markdown
  website/docs/upgrading.html.markdown
Labels: documentation, size/L

#89 Add the consul_service_health data source
  consul/data_source_consul_service_health.go
  consul/data_source_consul_service_health_test.go
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
  consul/resource_provider.go
  website/consul.erb
  website/docs/d/service_health.html.markdown
Labels: dependencies, documentation, enhancement, size/XL

#115 Update changelog
  CHANGELOG.md
  consul/data_source_consul_service_health.go
  consul/resource_consul_acl_token.go
  consul/resource_consul_keys.go
  consul/resource_consul_node_test.go
  consul/resource_consul_prepared_query_test.go
  website/docs/d/service_health.html.markdown
Labels: documentation, size/S

#116 Fix examples in acl_token and acl_policy documentation
  website/docs/r/acl_policy.html.markdown
  website/docs/r/acl_token.html.markdown
Labels: documentation, size/XS

#117 Mark local attribute of consul_acl_token as ForceNew
  CHANGELOG.md
  consul/resource_consul_acl_token.go
  consul/resource_consul_acl_token_test.go
Labels: size/XS

#120 Fix typography in upgrading guide
  website/docs/upgrading.html.markdown
Labels: documentation, size/XS
