Repository hashicorp/terraform-provider-consul, pull requests merged in 2019-04, with the labels that each got.

#60 Add resources for ACLs & tokens management (new ACLs v1.4)
  GNUmakefile
  README.md
  consul/resource_consul_acl_policy.go
  consul/resource_consul_acl_policy_test.go
  consul/resource_consul_acl_token.go
  consul/resource_consul_acl_token_test.go
  consul/resource_consul_prepared_query_test.go
  consul/resource_consul_service_test.go
  consul/resource_provider.go
  consul_test.hcl
  website/consul.erb
  website/docs/r/acl_policy.html.markdown
  website/docs/r/acl_token.html.markdown
Labels: dependencies, documentation, size/XL

#96 Update Changelog with upcoming changes
  CHANGELOG.md
Labels: size/XS

#99 Default datacenter to "" if not readable in /agent/self
  consul/resource_consul_keys.go
Labels: size/XS

#106 Mark token in nested blocks as sensitive
  consul/query_options.go
  consul/resource_provider_test.go
Labels: size/S
