Repository hashicorp/terraform-provider-consul, pull requests merged in 2019-07, with the labels that each got.

#121 Fix consul_prepared_query handling of default values for failover, dns and template
  CHANGELOG.md
  consul/resource_consul_prepared_query.go
  consul/resource_consul_prepared_query_test.go
Labels: size/M

#135 Fix issue query_options are not read #134
  consul/data_source_consul_services_test.go
  consul/query_options.go
Labels: size/M

#136 Document meta attribute on consul_service resource
  website/docs/r/service.html.markdown
Labels: documentation, size/XS

#130 Add a new resource that links a token to a policy
  consul/resource_consul_acl_policy_test.go
  consul/resource_consul_acl_token.go
  consul/resource_consul_acl_token_policy_attachment.go
  consul/resource_consul_acl_token_policy_attachment_test.go
  consul/resource_consul_acl_token_test.go
  consul/resource_provider.go
  website/consul.erb
  website/docs/r/acl_token.html.markdown
  website/docs/r/acl_token_policy_attachment.html.markdown
Labels: documentation, size/XL
