Repository hashicorp/terraform-provider-consul, pull requests merged in 2019-02, with the labels that each got.

#83 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  consul/data_source_consul_agent_config.go
  consul/data_source_consul_key_prefix.go
  consul/data_source_consul_key_prefix_test.go
  consul/data_source_consul_keys.go
  consul/data_source_consul_keys_test.go
  consul/data_source_consul_nodes.go
  consul/data_source_consul_nodes_test.go
  consul/data_source_consul_service.go
  consul/data_source_consul_service_test.go
  consul/data_source_consul_services.go
  consul/data_source_consul_services_test.go
  consul/query_options.go
  consul/resource_consul_agent_service.go
  consul/resource_consul_agent_service_test.go
  consul/resource_consul_catalog_entry.go
  consul/resource_consul_catalog_entry_test.go
  consul/resource_consul_intention.go
  consul/resource_consul_intention_test.go
  consul/resource_consul_key_prefix.go
  consul/resource_consul_key_prefix_test.go
  consul/resource_consul_keys.go
  consul/resource_consul_keys_test.go
  consul/resource_consul_node.go
  consul/resource_consul_node_test.go
  consul/resource_consul_prepared_query.go
  consul/resource_consul_prepared_query_test.go
  consul/resource_consul_service.go
  consul/resource_consul_service_test.go
  consul/resource_provider.go
Labels: size/XL

#90 Fix consul_service datasource title in documentation
  website/docs/d/service.html.markdown
Labels: documentation, size/XS

#75 Add documentation for datacenter attribute in consul_node resource
  website/docs/r/node.html.markdown
Labels: size/XS

#84 Add consul_autopilot_health data source
  consul/data_source_consul_autopilot_health.go
  consul/data_source_consul_autopilot_health_test.go
  consul/resource_provider.go
  website/consul.erb
  website/docs/d/autopilot_health.html.markdown
Labels: documentation, size/L

#71 Add flags support to resource consul_keys
  consul/data_source_consul_key_prefix.go
  consul/data_source_consul_keys.go
  consul/key_client.go
  consul/resource_consul_key_prefix.go
  consul/resource_consul_key_prefix_test.go
  consul/resource_consul_keys.go
  consul/resource_consul_keys_migrate_test.go
  consul/resource_consul_keys_test.go
  website/docs/r/key_prefix.html.markdown
  website/docs/r/keys.html.markdown
Labels: documentation, size/XL

#73 Mark Consul token as sensitive
  consul/data_source_consul_key_prefix.go
  consul/data_source_consul_keys.go
  consul/resource_consul_catalog_entry.go
  consul/resource_consul_key_prefix.go
  consul/resource_consul_keys.go
  consul/resource_consul_node.go
  consul/resource_consul_prepared_query.go
  consul/resource_provider.go
  consul/resource_provider_test.go
Labels: size/M
