Repository hashicorp/terraform-provider-consul, pull requests merged in 2020-09, with the labels that each got.

#220 Allow specifying TLS Certificates via PEM strings
  consul/config.go
  consul/resource_provider.go
  consul/resource_provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#219 Correctly handles environment variables for the protocol scheme
  consul/resource_provider.go
Labels: size/XS

#218 Add support for the node binding rule
  consul/resource_consul_acl_binding_rule.go
  consul/resource_consul_acl_binding_rule_test.go
Labels: size/M
