Repository hashicorp/terraform-provider-consul, pull requests merged in 2020-02, with the labels that each got.

#179 Fix typo in consul_acl_token_policy_attachment documentation
  website/docs/r/acl_token_policy_attachment.html.markdown
Labels: documentation, size/XS

#181 Update tests for Consul 1.7.0
  consul/data_source_consul_service_health_test.go
  consul/data_source_consul_service_test.go
  consul_test.hcl
Labels: size/XS

#182 Add import support to consul_acl_role
  consul/resource_consul_acl_role.go
  consul/resource_consul_acl_role_test.go
  website/docs/r/acl_role.markdown
Labels: documentation, size/M

#184 Fix error message in consul_acl_token datasource
  consul/data_source_consul_acl_token_secret_id.go
Labels: size/XS
